spring:
  application:
    name: WeatherApiConsuming
    ApiKey: ${API_KEY}
    cors:
      allowed-origins: ${URL_CORS}:localhost:4200
  cache:
    type: redis
    redis:
      time-to-live: 1h
  data:
    redis:
      url: ${SPRING_DATA_REDIS_URL:redis://localhost:6379}
