spring:
  application:
    name: WeatherApiConsuming
    cors:
      allowed-origins: "https://weather-frontend-qxwf.onrender.com"
  cache:
    type: redis
    redis:
      time-to-live: 5h
  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}

